Portfolio: Desktop version
Izebiafe/my-protfolio pull request #4
Opened 2023-05-12 15:12 UTC by Izebiafe

- used correct git flow.
- followed proper indentation using linter
- followed the figma design to build a responsive portfolio.

2023-05-12 16:41 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @Izebiafe, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

## To Highlight 👍

- Descriptive Pull Request Title and Summary. ✔️
- Media Query Perfectly used ✔️
- Flexbox and Grid in order to layout the elements ✔️
- Good use of Github flow ✔️

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers... and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 16:41 UTC, brainconnect93 commented on assets/css/style.css
> +  }
- [ ] Great effort working on your `desktop version` but currently your work cards need some attention and I would like you to stick to the Figma design as much as possible, In the Figma design, the `2nd` and `4th` card has a kind of reverse in content whereby the image goes to the right side and other content is on the left side. Kindly implement this kind of reversed property in your cards too in order to have a perfect replica of the Figma design. 

Figma Design 👇 

![org card](https://github.com/Izebiafe/my-protfolio/assets/78634841/db4da507-dcc7-425f-9fb4-61da1031c8d1)

2023-05-12 16:41 UTC, brainconnect93 commented on assets/css/style.css
> +  }
- [ ] I would kindly suggest you stick with the Figma design as much as possible when designing your desktop version of the project. Currently, your contact section of the project does not look like what we have in the Figma design. Kindly reduce the width of the form and make it properly aligned.

Possible Implementation 👇 

  - Kindly reduce the width in the  class `.contact input[type="text"], .contact input[type="email"]`, and `.contact textarea` from `100%` to `50%` and add a margin of `0 auto`
  - Also kindly add this class `.contact .contact-text p` in your `media-query` for desktop design and give it the below properties

```CSS
.contact .contact-text p {
    font-style: normal;
    font-weight: 400;
    font-size: 20px;
    line-height: 28px;
    color: #ebebff;
    width: 70%;
    margin: 15px auto;
}
```


- [ ] Also i would kindly suggest you give all the buttons some effect as seen in the Figma design `i.e hover, active, enabled` etc.

2023-05-13 00:55 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @Izebiafe 🙋‍♀️

Good job so far implementing the changes suggested by the previous reviewer . **_However, ther are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Great job with CSS
- ✅ Good branch name
- ✅ Correct Linters

## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Please check the comments under the review._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 00:55 UTC, KanzaTahreem commented on assets/css/utilites.css
> +}
- [ ] Well done for implementing the button interactions 🥇🥇 However, I noticed that you missed the `box-shadow` property for `hover` which is `box-shadow: 0px 8px 16px rgba(64, 83, 252, 0.24);` Please add this ✨

2023-05-13 00:55 UTC, KanzaTahreem commented on assets/css/style.css
> +  }
- [OPTIONAL] Good job for reversing the cards as suggested by the reviewer 🥇🥇 Please consider fixing the width of the images in project cards to get a design close to the Figma template as much as possible 🤓🔨 One possible implementation can be 👇

```
.card .card-img {
  // other properties
  flex: 1.5;
}

content {
  flex: 2;
}
```

2023-05-13 01:21 UTC, Efiamotu-1 approved these changes
Hi @Izebiafe , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 04:15 UTC, merged